package com.example.DatabaseInit.Enum;

public enum EPermission {
    ACCESS_USER,
    MODIFY_USER,
    CREATE_USER,
    DELETE_USER,
    ACCESS_CONTACT,
    MODIFY_CONTACT,
    CREATE_CONTACT,
    DELETE_CONTACT,
    ACCESS_INTERACTION,
    MODIFY_INTERACTION,
    CREATE_INTERACTION,
    DELETE_INTERACTION,
    ACCESS_COMPANY,
    CREATE_COMPANY,
    MODIFY_COMPANY,
    DELETE_COMPANY,
}
